<?php
add_action( 'admin_head', function() {
	?>
	<style>
	body { font-family: 'Proxima Nova', Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif;}
	</style>
	<?php
});

add_action( 'after_setup_theme', function() {
	add_editor_style( $GLOBALS['template_url'] . '/admin/editor.css' );
});

if( function_exists( 'acf_add_options_page' )) {
	acf_add_options_page(array(
		'page_title' => 'Homepage',
		'position' => 3
	));
}

if( function_exists('register_field_group') ):
	register_field_group(array (
		'key' => 'group_5404bbc01c398',
		'title' => 'Featured Posts',
		'fields' => array (
			array (
				'key' => 'field_5404bbd68d26d',
				'label' => 'Featured Posts',
				'name' => 'featured_posts',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'min' => 1,
				'max' => '',
				'layout' => 'row',
				'button_label' => 'Add Featured Post',
				'sub_fields' => array (
					array (
						'key' => 'field_5404bbed8d26e',
						'label' => 'Post',
						'name' => 'post',
						'prefix' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'column_width' => '',
						'post_type' => array (
							0 => 'post',
						),
						'taxonomy' => '',
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'id',
						'ui' => 1,
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-homepage',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_5404b31af256e',
		'title' => 'Interviewee',
		'fields' => array (
			array (
				'key' => 'field_52d58f366df37',
				'label' => 'Avatar',
				'name' => 'profile-avatar',
				'prefix' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'return_format' => 'url',
			),
			array (
				'key' => 'field_52d58f456df38',
				'label' => 'Name',
				'name' => 'profile-name',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_52d58f4b6df39',
				'label' => 'Twitter Handle',
				'name' => 'profile-handle',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_52d58f696df3a',
				'label' => 'Description',
				'name' => 'description',
				'prefix' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'new_lines' => 'br',
				'readonly' => 0,
				'disabled' => 0,
				'rows' => '',
			),
			array (
				'key' => 'field_52d58f756df3b',
				'label' => 'Location',
				'name' => 'profile-location',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_52d58f7f6df3c',
				'label' => 'URL',
				'name' => 'profile-url',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_category',
					'operator' => '==',
					'value' => 'category:interviews',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_5404b37984a71',
		'title' => 'Posts',
		'fields' => array (
			array (
				'key' => 'field_5404bcde2f4aa',
				'label' => 'Alternate Title',
				'name' => 'alt_title',
				'prefix' => '',
				'type' => 'text',
				'instructions' => 'A shorter version of the title for use in grid tiles. Not required if there\'s a subject/subtitle.',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5404bd002f4ab',
				'label' => 'Subject',
				'name' => 'subject',
				'prefix' => '',
				'type' => 'text',
				'instructions' => 'The interviewee or product name being discussed in the article.',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5404bd202f4ac',
				'label' => 'Subtitle',
				'name' => 'subtitle',
				'prefix' => '',
				'type' => 'text',
				'instructions' => 'The significance of the person or product.',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));
endif;